// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file cosmos/store/streaming/abci/grpc.proto (package cosmos.store.streaming.abci, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { RequestBeginBlock, RequestDeliverTx, RequestEndBlock, ResponseBeginBlock, ResponseCommit, ResponseDeliverTx, ResponseEndBlock } from "../../../../tendermint/abci/types_pb.js";
import { StoreKVPair } from "../../v1beta1/listening_pb.js";

/**
 * ListenBeginBlockRequest is the request type for the ListenBeginBlock RPC method
 *
 * @generated from message cosmos.store.streaming.abci.ListenBeginBlockRequest
 */
export class ListenBeginBlockRequest extends Message<ListenBeginBlockRequest> {
  /**
   * @generated from field: tendermint.abci.RequestBeginBlock req = 1;
   */
  req?: RequestBeginBlock;

  /**
   * @generated from field: tendermint.abci.ResponseBeginBlock res = 2;
   */
  res?: ResponseBeginBlock;

  constructor(data?: PartialMessage<ListenBeginBlockRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cosmos.store.streaming.abci.ListenBeginBlockRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "req", kind: "message", T: RequestBeginBlock },
    { no: 2, name: "res", kind: "message", T: ResponseBeginBlock },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListenBeginBlockRequest {
    return new ListenBeginBlockRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListenBeginBlockRequest {
    return new ListenBeginBlockRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListenBeginBlockRequest {
    return new ListenBeginBlockRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListenBeginBlockRequest | PlainMessage<ListenBeginBlockRequest> | undefined, b: ListenBeginBlockRequest | PlainMessage<ListenBeginBlockRequest> | undefined): boolean {
    return proto3.util.equals(ListenBeginBlockRequest, a, b);
  }
}

/**
 * ListenBeginBlockResponse is the response type for the ListenBeginBlock RPC method
 *
 * @generated from message cosmos.store.streaming.abci.ListenBeginBlockResponse
 */
export class ListenBeginBlockResponse extends Message<ListenBeginBlockResponse> {
  constructor(data?: PartialMessage<ListenBeginBlockResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cosmos.store.streaming.abci.ListenBeginBlockResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListenBeginBlockResponse {
    return new ListenBeginBlockResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListenBeginBlockResponse {
    return new ListenBeginBlockResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListenBeginBlockResponse {
    return new ListenBeginBlockResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListenBeginBlockResponse | PlainMessage<ListenBeginBlockResponse> | undefined, b: ListenBeginBlockResponse | PlainMessage<ListenBeginBlockResponse> | undefined): boolean {
    return proto3.util.equals(ListenBeginBlockResponse, a, b);
  }
}

/**
 * ListenEndBlockRequest is the request type for the ListenEndBlock RPC method
 *
 * @generated from message cosmos.store.streaming.abci.ListenEndBlockRequest
 */
export class ListenEndBlockRequest extends Message<ListenEndBlockRequest> {
  /**
   * @generated from field: tendermint.abci.RequestEndBlock req = 1;
   */
  req?: RequestEndBlock;

  /**
   * @generated from field: tendermint.abci.ResponseEndBlock res = 2;
   */
  res?: ResponseEndBlock;

  constructor(data?: PartialMessage<ListenEndBlockRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cosmos.store.streaming.abci.ListenEndBlockRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "req", kind: "message", T: RequestEndBlock },
    { no: 2, name: "res", kind: "message", T: ResponseEndBlock },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListenEndBlockRequest {
    return new ListenEndBlockRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListenEndBlockRequest {
    return new ListenEndBlockRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListenEndBlockRequest {
    return new ListenEndBlockRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListenEndBlockRequest | PlainMessage<ListenEndBlockRequest> | undefined, b: ListenEndBlockRequest | PlainMessage<ListenEndBlockRequest> | undefined): boolean {
    return proto3.util.equals(ListenEndBlockRequest, a, b);
  }
}

/**
 * ListenEndBlockResponse is the response type for the ListenEndBlock RPC method
 *
 * @generated from message cosmos.store.streaming.abci.ListenEndBlockResponse
 */
export class ListenEndBlockResponse extends Message<ListenEndBlockResponse> {
  constructor(data?: PartialMessage<ListenEndBlockResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cosmos.store.streaming.abci.ListenEndBlockResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListenEndBlockResponse {
    return new ListenEndBlockResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListenEndBlockResponse {
    return new ListenEndBlockResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListenEndBlockResponse {
    return new ListenEndBlockResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListenEndBlockResponse | PlainMessage<ListenEndBlockResponse> | undefined, b: ListenEndBlockResponse | PlainMessage<ListenEndBlockResponse> | undefined): boolean {
    return proto3.util.equals(ListenEndBlockResponse, a, b);
  }
}

/**
 * ListenDeliverTxRequest is the request type for the ListenDeliverTx RPC method
 *
 * @generated from message cosmos.store.streaming.abci.ListenDeliverTxRequest
 */
export class ListenDeliverTxRequest extends Message<ListenDeliverTxRequest> {
  /**
   * explicitly pass in block height as neither RequestDeliverTx or ResponseDeliverTx contain it
   *
   * @generated from field: int64 block_height = 1;
   */
  blockHeight = protoInt64.zero;

  /**
   * @generated from field: tendermint.abci.RequestDeliverTx req = 2;
   */
  req?: RequestDeliverTx;

  /**
   * @generated from field: tendermint.abci.ResponseDeliverTx res = 3;
   */
  res?: ResponseDeliverTx;

  constructor(data?: PartialMessage<ListenDeliverTxRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cosmos.store.streaming.abci.ListenDeliverTxRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "block_height", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "req", kind: "message", T: RequestDeliverTx },
    { no: 3, name: "res", kind: "message", T: ResponseDeliverTx },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListenDeliverTxRequest {
    return new ListenDeliverTxRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListenDeliverTxRequest {
    return new ListenDeliverTxRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListenDeliverTxRequest {
    return new ListenDeliverTxRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListenDeliverTxRequest | PlainMessage<ListenDeliverTxRequest> | undefined, b: ListenDeliverTxRequest | PlainMessage<ListenDeliverTxRequest> | undefined): boolean {
    return proto3.util.equals(ListenDeliverTxRequest, a, b);
  }
}

/**
 * ListenDeliverTxResponse is the response type for the ListenDeliverTx RPC method
 *
 * @generated from message cosmos.store.streaming.abci.ListenDeliverTxResponse
 */
export class ListenDeliverTxResponse extends Message<ListenDeliverTxResponse> {
  constructor(data?: PartialMessage<ListenDeliverTxResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cosmos.store.streaming.abci.ListenDeliverTxResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListenDeliverTxResponse {
    return new ListenDeliverTxResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListenDeliverTxResponse {
    return new ListenDeliverTxResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListenDeliverTxResponse {
    return new ListenDeliverTxResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListenDeliverTxResponse | PlainMessage<ListenDeliverTxResponse> | undefined, b: ListenDeliverTxResponse | PlainMessage<ListenDeliverTxResponse> | undefined): boolean {
    return proto3.util.equals(ListenDeliverTxResponse, a, b);
  }
}

/**
 * ListenCommitRequest is the request type for the ListenCommit RPC method
 *
 * @generated from message cosmos.store.streaming.abci.ListenCommitRequest
 */
export class ListenCommitRequest extends Message<ListenCommitRequest> {
  /**
   * explicitly pass in block height as ResponseCommit does not contain this info
   *
   * @generated from field: int64 block_height = 1;
   */
  blockHeight = protoInt64.zero;

  /**
   * @generated from field: tendermint.abci.ResponseCommit res = 2;
   */
  res?: ResponseCommit;

  /**
   * @generated from field: repeated cosmos.store.v1beta1.StoreKVPair change_set = 3;
   */
  changeSet: StoreKVPair[] = [];

  constructor(data?: PartialMessage<ListenCommitRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cosmos.store.streaming.abci.ListenCommitRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "block_height", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "res", kind: "message", T: ResponseCommit },
    { no: 3, name: "change_set", kind: "message", T: StoreKVPair, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListenCommitRequest {
    return new ListenCommitRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListenCommitRequest {
    return new ListenCommitRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListenCommitRequest {
    return new ListenCommitRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListenCommitRequest | PlainMessage<ListenCommitRequest> | undefined, b: ListenCommitRequest | PlainMessage<ListenCommitRequest> | undefined): boolean {
    return proto3.util.equals(ListenCommitRequest, a, b);
  }
}

/**
 * ListenCommitResponse is the response type for the ListenCommit RPC method
 *
 * @generated from message cosmos.store.streaming.abci.ListenCommitResponse
 */
export class ListenCommitResponse extends Message<ListenCommitResponse> {
  constructor(data?: PartialMessage<ListenCommitResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cosmos.store.streaming.abci.ListenCommitResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListenCommitResponse {
    return new ListenCommitResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListenCommitResponse {
    return new ListenCommitResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListenCommitResponse {
    return new ListenCommitResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListenCommitResponse | PlainMessage<ListenCommitResponse> | undefined, b: ListenCommitResponse | PlainMessage<ListenCommitResponse> | undefined): boolean {
    return proto3.util.equals(ListenCommitResponse, a, b);
  }
}

