// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file cosmos/circuit/v1/query.proto (package cosmos.circuit.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AccountResponse, AccountsResponse, DisabledListResponse, QueryAccountRequest, QueryAccountsRequest, QueryDisabledListRequest } from "./query_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Msg defines the crisis Msg service.
 *
 * @generated from service cosmos.circuit.v1.Query
 */
export const Query = {
  typeName: "cosmos.circuit.v1.Query",
  methods: {
    /**
     * Account returns account permissions.
     *
     * @generated from rpc cosmos.circuit.v1.Query.Account
     */
    account: {
      name: "Account",
      I: QueryAccountRequest,
      O: AccountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Account returns account permissions.
     *
     * @generated from rpc cosmos.circuit.v1.Query.Accounts
     */
    accounts: {
      name: "Accounts",
      I: QueryAccountsRequest,
      O: AccountsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * DisabledList returns a list of disabled message urls
     *
     * @generated from rpc cosmos.circuit.v1.Query.DisabledList
     */
    disabledList: {
      name: "DisabledList",
      I: QueryDisabledListRequest,
      O: DisabledListResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

