// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file cosmos/circuit/v1/tx.proto (package cosmos.circuit.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgAuthorizeCircuitBreaker, MsgAuthorizeCircuitBreakerResponse, MsgResetCircuitBreaker, MsgResetCircuitBreakerResponse, MsgTripCircuitBreaker, MsgTripCircuitBreakerResponse } from "./tx_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Msg defines the crisis Msg service.
 *
 * @generated from service cosmos.circuit.v1.Msg
 */
export const Msg = {
  typeName: "cosmos.circuit.v1.Msg",
  methods: {
    /**
     * AuthorizeCircuitBreaker allows a super-admin to grant (or revoke) another
     * account's circuit breaker permissions.
     *
     * @generated from rpc cosmos.circuit.v1.Msg.AuthorizeCircuitBreaker
     */
    authorizeCircuitBreaker: {
      name: "AuthorizeCircuitBreaker",
      I: MsgAuthorizeCircuitBreaker,
      O: MsgAuthorizeCircuitBreakerResponse,
      kind: MethodKind.Unary,
    },
    /**
     * TripCircuitBreaker pauses processing of Msg's in the state machine.
     *
     * @generated from rpc cosmos.circuit.v1.Msg.TripCircuitBreaker
     */
    tripCircuitBreaker: {
      name: "TripCircuitBreaker",
      I: MsgTripCircuitBreaker,
      O: MsgTripCircuitBreakerResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ResetCircuitBreaker resumes processing of Msg's in the state machine that
     * have been been paused using TripCircuitBreaker.
     *
     * @generated from rpc cosmos.circuit.v1.Msg.ResetCircuitBreaker
     */
    resetCircuitBreaker: {
      name: "ResetCircuitBreaker",
      I: MsgResetCircuitBreaker,
      O: MsgResetCircuitBreakerResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

