// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file noble/forwarding/v1/query.proto (package noble.forwarding.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryAddress, QueryAddressResponse, QueryStats, QueryStatsByChannel, QueryStatsByChannelResponse, QueryStatsResponse } from "./query_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service noble.forwarding.v1.Query
 */
export const Query = {
  typeName: "noble.forwarding.v1.Query",
  methods: {
    /**
     * @generated from rpc noble.forwarding.v1.Query.Address
     */
    address: {
      name: "Address",
      I: QueryAddress,
      O: QueryAddressResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc noble.forwarding.v1.Query.Stats
     */
    stats: {
      name: "Stats",
      I: QueryStats,
      O: QueryStatsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc noble.forwarding.v1.Query.StatsByChannel
     */
    statsByChannel: {
      name: "StatsByChannel",
      I: QueryStatsByChannel,
      O: QueryStatsByChannelResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

